### ISSUE TITLE
still getting this error after running for a long time

### ISSUE THREAD

**Issue by Barmem** [depthbomb/Scraps#21]
```
"System.Net.Http""   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Scraps.GUI.Services.RaffleService.ScanRafflesAsync() in C:\Users\reese\source\repos\Scraps\Scraps.GUI\Services\Raffle\RaffleService.cs:line 243
   at Scraps.GUI.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.GUI\Services\Raffle\RaffleService.cs:line 139"
```

**Comment by depthbomb** [comment]
This error is possibly due to your internet briefly losing connection while running. If you leave Scraps running and your computer goes to sleep then that may also cause it to lose connection.

**Comment by depthbomb** [comment]
Release [4.6.1.0](https://github.com/depthbomb/Scraps/releases/tag/4.6.1.0) adds a new launch flag that you can use that might remedy this problem.
