### ISSUE TITLE
Raffle Script not starting (http error 403?)

### ISSUE THREAD

**Issue by Anonymous8623** [depthbomb/Scraps#41]
**Raffle Script not starting**
immediately upon pressing start the script gets snagged by an error message (using older releases doesn't solve it)

**Error message:**
"System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Scraps.GUI.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.GUI\Services\Raffle\RaffleService.cs:line 239
   at Scraps.GUI.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.GUI\Services\Raffle\RaffleService.cs:line 112

**Note**
(idk why *C:\Users\reese\source\...* is there it wasn't present in older releases, there is only one user on my PC)

**Comment by poopslayer4000** [comment]
Is there a fix to this?

**Comment by bruhmomentobama** [comment]
Give her/him/they/helicopter/tank/obama some time

**Comment by bruhmomentobama** [comment]
@depthbomb To repeat my previous suggestion, to either code a browser for the bot so it's not just invisible and you can confirm any captchas or the new browser checker feature, or have it use firefox or chrome but keep the windows hidden, or my new idea which is to completely transform the Scraps to a extension for chrome and firefox.
