### ISSUE TITLE
System.Net.Http.HttpRequestException: Unable to get string: Forbidden

### ISSUE THREAD

**Issue by mosheernser880** [depthbomb/Scraps#51]
21:36:35 Starting
21:36:35 Creating HTTP client
21:36:35 Created HTTP client (cookie="**********************",352)
21:36:35 Sending GET request to "/"
21:36:35 "System.Net.Http.HttpRequestException: Unable to get string: Forbidden
   at Scraps.GUI.Services.RaffleService.GetStringAsync(String path) in C:\Users\reese\source\repos\Scraps\Scraps.GUI\Services\Raffle\RaffleService.cs:line 564
   at Scraps.GUI.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.GUI\Services\Raffle\RaffleService.cs:line 251
   at Scraps.GUI.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.GUI\Services\Raffle\RaffleService.cs:line 134"
21:36:35 Stopped

**Comment by depthbomb** [comment]
Without any more info this problem cannot be diagnosed.
Please ensure that you are not being blocked by CloudFlare (by visiting the website normally) and that your cookie value is correct.
