### ISSUE TITLE
System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by mosheernser880** [depthbomb/Scraps#52]
Logs(i hid only the cookie):
2022-09-13 09:06:19.1062 │ DEBUG │           WebViewService.IsRuntimeInstalled │ WebView2 runtime is installed
2022-09-13 09:06:19.1896 │ DEBUG │     UpdateService.CheckUntilUpdateAvailable │ Started update check loop
2022-09-13 09:06:19.1896 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:06:19.7101 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Runner" to tabs with image index 0
2022-09-13 09:06:19.7232 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Won Raffles" to tabs with image index 1
2022-09-13 09:06:19.7373 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Settings" to tabs with image index 2
2022-09-13 09:06:19.7373 │ DEBUG │                    MainForm.AddControlToTab │ Added control "About" to tabs with image index 3
2022-09-13 09:06:19.8058 │ DEBUG │ AnnouncementService.FetchAnnouncementsAsync │ Fetching announcements
2022-09-13 09:06:20.3658 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:06:31.9324 │ INFO  │                    RaffleService.StartAsync │ Starting
2022-09-13 09:06:31.9613 │ DEBUG │              RaffleService.CreateHttpClient │ Creating HTTP client
2022-09-13 09:06:31.9613 │ DEBUG │              RaffleService.CreateHttpClient │ Created HTTP client (cookie="ХХХ",352)
2022-09-13 09:06:31.9613 │ DEBUG │                RaffleService.GetStringAsync │ Sending GET request to "/"
2022-09-13 09:06:32.3553 │ FATAL │                    RaffleService.StartAsync │ "System.Net.Http.HttpRequestException: Unable to get string: Forbidden
   at Scraps.Next.Services.RaffleService.GetStringAsync(String path) in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 579
   at Scraps.Next.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 278
   at Scraps.Next.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 165"
2022-09-13 09:06:32.3913 │ INFO  │                    RaffleService.StartAsync │ Stopped
2022-09-13 09:07:20.5458 │ DEBUG │           WebViewService.IsRuntimeInstalled │ WebView2 runtime is installed
2022-09-13 09:07:20.6146 │ DEBUG │     UpdateService.CheckUntilUpdateAvailable │ Started update check loop
2022-09-13 09:07:20.6146 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:07:20.9792 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Runner" to tabs with image index 0
2022-09-13 09:07:20.9792 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Won Raffles" to tabs with image index 1
2022-09-13 09:07:20.9900 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Settings" to tabs with image index 2
2022-09-13 09:07:20.9900 │ DEBUG │                    MainForm.AddControlToTab │ Added control "About" to tabs with image index 3
2022-09-13 09:07:21.0969 │ DEBUG │ AnnouncementService.FetchAnnouncementsAsync │ Fetching announcements
2022-09-13 09:07:21.6578 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:07:26.6568 │ INFO  │                    RaffleService.StartAsync │ Starting
2022-09-13 09:07:26.6732 │ DEBUG │              RaffleService.CreateHttpClient │ Creating HTTP client
2022-09-13 09:07:26.6732 │ DEBUG │              RaffleService.CreateHttpClient │ Created HTTP client (cookie="ХХХ",352)
2022-09-13 09:07:26.6732 │ DEBUG │                RaffleService.GetStringAsync │ Sending GET request to "/"
2022-09-13 09:07:26.8803 │ FATAL │                    RaffleService.StartAsync │ "System.Net.Http.HttpRequestException: Unable to get string: Forbidden
   at Scraps.Next.Services.RaffleService.GetStringAsync(String path) in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 579
   at Scraps.Next.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 278
   at Scraps.Next.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 165"
2022-09-13 09:07:26.8919 │ INFO  │                    RaffleService.StartAsync │ Stopped

CloudFlare does not block me, the site opens in a regular browser, the site opens in the program. What's wrong?
![bandicam 2022-09-13 09-13-14-021](https://user-images.githubusercontent.com/98277065/189824032-e63d5d40-53a0-4d4d-b03d-d45414ade45f.jpg)

**Comment by depthbomb** [comment]
Could you provide an excerpt of your logs without the partial cookie value censored? It is only the first 32 characters of the cookie value so it is safe to provide.

**Comment by mosheernser880** [comment]
2022-09-13 09:06:19.1062 │ DEBUG │           WebViewService.IsRuntimeInstalled │ WebView2 runtime is installed
2022-09-13 09:06:19.1896 │ DEBUG │     UpdateService.CheckUntilUpdateAvailable │ Started update check loop
2022-09-13 09:06:19.1896 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:06:19.7101 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Runner" to tabs with image index 0
2022-09-13 09:06:19.7232 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Won Raffles" to tabs with image index 1
2022-09-13 09:06:19.7373 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Settings" to tabs with image index 2
2022-09-13 09:06:19.7373 │ DEBUG │                    MainForm.AddControlToTab │ Added control "About" to tabs with image index 3
2022-09-13 09:06:19.8058 │ DEBUG │ AnnouncementService.FetchAnnouncementsAsync │ Fetching announcements
2022-09-13 09:06:20.3658 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:06:31.9324 │ INFO  │                    RaffleService.StartAsync │ Starting
2022-09-13 09:06:31.9613 │ DEBUG │              RaffleService.CreateHttpClient │ Creating HTTP client
2022-09-13 09:06:31.9613 │ DEBUG │              RaffleService.CreateHttpClient │ Created HTTP client (cookie="bG9naW5fcmVkaXJlY3R8czoxNzoiaHR0",352)
2022-09-13 09:06:31.9613 │ DEBUG │                RaffleService.GetStringAsync │ Sending GET request to "/"
2022-09-13 09:06:32.3553 │ FATAL │                    RaffleService.StartAsync │ "System.Net.Http.HttpRequestException: Unable to get string: Forbidden
   at Scraps.Next.Services.RaffleService.GetStringAsync(String path) in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 579
   at Scraps.Next.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 278
   at Scraps.Next.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 165"
2022-09-13 09:06:32.3913 │ INFO  │                    RaffleService.StartAsync │ Stopped
2022-09-13 09:07:20.5458 │ DEBUG │           WebViewService.IsRuntimeInstalled │ WebView2 runtime is installed
2022-09-13 09:07:20.6146 │ DEBUG │     UpdateService.CheckUntilUpdateAvailable │ Started update check loop
2022-09-13 09:07:20.6146 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:07:20.9792 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Runner" to tabs with image index 0
2022-09-13 09:07:20.9792 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Won Raffles" to tabs with image index 1
2022-09-13 09:07:20.9900 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Settings" to tabs with image index 2
2022-09-13 09:07:20.9900 │ DEBUG │                    MainForm.AddControlToTab │ Added control "About" to tabs with image index 3
2022-09-13 09:07:21.0969 │ DEBUG │ AnnouncementService.FetchAnnouncementsAsync │ Fetching announcements
2022-09-13 09:07:21.6578 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:07:26.6568 │ INFO  │                    RaffleService.StartAsync │ Starting
2022-09-13 09:07:26.6732 │ DEBUG │              RaffleService.CreateHttpClient │ Creating HTTP client
2022-09-13 09:07:26.6732 │ DEBUG │              RaffleService.CreateHttpClient │ Created HTTP client (cookie="bG9naW5fcmVkaXJlY3R8czoxNzoiaHR0",352)
2022-09-13 09:07:26.6732 │ DEBUG │                RaffleService.GetStringAsync │ Sending GET request to "/"
2022-09-13 09:07:26.8803 │ FATAL │                    RaffleService.StartAsync │ "System.Net.Http.HttpRequestException: Unable to get string: Forbidden
   at Scraps.Next.Services.RaffleService.GetStringAsync(String path) in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 579
   at Scraps.Next.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 278
   at Scraps.Next.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 165"
2022-09-13 09:07:26.8919 │ INFO  │                    RaffleService.StartAsync │ Stopped
2022-09-13 09:12:16.5583 │ DEBUG │           WebViewService.IsRuntimeInstalled │ WebView2 runtime is installed
2022-09-13 09:12:16.6469 │ DEBUG │     UpdateService.CheckUntilUpdateAvailable │ Started update check loop
2022-09-13 09:12:16.6469 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:12:16.9867 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Runner" to tabs with image index 0
2022-09-13 09:12:16.9867 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Won Raffles" to tabs with image index 1
2022-09-13 09:12:16.9867 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Settings" to tabs with image index 2
2022-09-13 09:12:16.9867 │ DEBUG │                    MainForm.AddControlToTab │ Added control "About" to tabs with image index 3
2022-09-13 09:12:17.0358 │ DEBUG │ AnnouncementService.FetchAnnouncementsAsync │ Fetching announcements
2022-09-13 09:12:17.6022 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:12:18.4533 │ INFO  │                    RaffleService.StartAsync │ Starting
2022-09-13 09:12:18.4683 │ DEBUG │              RaffleService.CreateHttpClient │ Creating HTTP client
2022-09-13 09:12:18.4683 │ DEBUG │              RaffleService.CreateHttpClient │ Created HTTP client (cookie="bG9naW5fcmVkaXJlY3R8czoxNzoiaHR0",352)
2022-09-13 09:12:18.4732 │ DEBUG │                RaffleService.GetStringAsync │ Sending GET request to "/"
2022-09-13 09:12:19.2663 │ FATAL │                    RaffleService.StartAsync │ "System.Net.Http.HttpRequestException: Unable to get string: Forbidden
   at Scraps.Next.Services.RaffleService.GetStringAsync(String path) in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 579
   at Scraps.Next.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 278
   at Scraps.Next.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 165"
2022-09-13 09:12:19.2793 │ INFO  │                    RaffleService.StartAsync │ Stopped
2022-09-13 09:13:17.6203 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:13:17.8897 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:14:17.8909 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:14:18.1514 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:15:18.1493 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:15:18.4111 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:16:18.4093 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:16:18.6948 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:17:18.6810 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:17:18.9471 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:18:18.9624 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:18:19.2854 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:19:19.2864 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:19:19.5456 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:24:16.2961 │ DEBUG │           WebViewService.IsRuntimeInstalled │ WebView2 runtime is installed
2022-09-13 09:24:16.3739 │ DEBUG │     UpdateService.CheckUntilUpdateAvailable │ Started update check loop
2022-09-13 09:24:16.4186 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-13 09:24:16.9360 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Runner" to tabs with image index 0
2022-09-13 09:24:16.9360 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Won Raffles" to tabs with image index 1
2022-09-13 09:24:16.9504 │ DEBUG │                    MainForm.AddControlToTab │ Added control "Settings" to tabs with image index 2
2022-09-13 09:24:16.9504 │ DEBUG │                    MainForm.AddControlToTab │ Added control "About" to tabs with image index 3
2022-09-13 09:24:16.9880 │ DEBUG │ AnnouncementService.FetchAnnouncementsAsync │ Fetching announcements
2022-09-13 09:24:17.7670 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-13 09:24:43.7870 │ INFO  │                    RaffleService.StartAsync │ Starting
2022-09-13 09:24:43.8005 │ DEBUG │              RaffleService.CreateHttpClient │ Creating HTTP client
2022-09-13 09:24:43.8005 │ DEBUG │              RaffleService.CreateHttpClient │ Created HTTP client (cookie="bG9naW5fcmVkaXJlY3R8czoxNzoiaHR0",352)
2022-09-13 09:24:43.8005 │ DEBUG │                RaffleService.GetStringAsync │ Sending GET request to "/"
2022-09-13 09:24:44.5889 │ FATAL │                    RaffleService.StartAsync │ "System.Net.Http.HttpRequestException: Unable to get string: Forbidden
   at Scraps.Next.Services.RaffleService.GetStringAsync(String path) in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 579
   at Scraps.Next.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 278
   at Scraps.Next.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 165"
2022-09-13 09:24:44.5995 │ INFO  │                    RaffleService.StartAsync │ Stopped

**Comment by depthbomb** [comment]
A new version will be released tomorrow that has improved logging which will better help diagnose this problem.

In the meantime, try closing the app and wiping all of your settings files located in `%LOCALAPPDATA%\Caprine_Logic\` and seeing if the problem persists. If it does then please submit an issue after updating to the new version.

**Comment by mosheernser880** [comment]
```2022-09-14 08:59:53.2918 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ Checking for updates
2022-09-14 08:59:53.6150 │ DEBUG │          UpdateService.CheckForUpdatesAsync │ No updates available
2022-09-14 08:59:56.5248 │ INFO  │                    RaffleService.StartAsync │ Starting
2022-09-14 08:59:56.5387 │ DEBUG │              RaffleService.CreateHttpClient │ Creating HTTP client
2022-09-14 08:59:56.5387 │ DEBUG │              RaffleService.CreateHttpClient │ Created HTTP client (cookie="bG9naW5fcmVkaXJlY3R8czoxNzoiaHR0"..."M2NhNWQ0NTU2YjVmZjkwNTVmZg%3D%3D",352)
2022-09-14 08:59:56.5387 │ DEBUG │                RaffleService.GetStringAsync │ Sending GET request to "/"
2022-09-14 08:59:56.7370 │ ERROR │                RaffleService.GetStringAsync │ Unable to get string: "Forbidden"
2022-09-14 08:59:56.7370 │ ERROR │                RaffleService.GetStringAsync │ <!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="robots" content="noindex,nofollow" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet" />
    

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)" />
            scrap.tf
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=74a6e6313e384991')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            scrap.tf needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/?__cf_chl_f_tk=E7vNErhJIa84spclKAVw2gt6HgcKtWIqLam_uX3iM3Y-1663135193-0-gaNycGzNB30" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="DIdL0h6bPEEL9BZQ63nNZ_ya12Ufq_nvV9GmxAiXosw-1663135193-0-Abn72Yn6RwostC1A7jN9q-S620KKK6aMvx10uneCvoysRvr6Q_VYDXDuhf9-Vo24DGwTu-JmCj96JcWhuJnnqltWGjKdL0Q0jD5drGATA11r5-YQpIZWPDnZAziT910WEvTQAIhSgSCLu7gmlV9OD8ta54b8e1kTAz-PUawrhp10_JjT3hu5KREQqDvNVkCLgGf0n3VFqpcXrCQruzYYSvfditScOXfu9nY3orwIHwT1IZfIYRrKZn0T0Iy78gsTzQ8rJmhkVcOxkV5dQ9lLRYRxQCMyoEE1IWAzB1QHN6fKc6dcWMpldQoD5tIJTLPU4L14XIZm-QnvXEeB9cP_-IAAO1Hj6N9nMv_Otm4DEqLYydI2jV33kpZ0PYXGRHMBfPWvtdHSWwWDqksawJfIWzESp1FtSIRP0Vnd0U4oGTkXk2xznhRE12a61Ktf2xxvbl3u61-TiyOx1i4kt9JA4hPqbUqTJIbQJgmJl2DAbVTkpBVAajHsl9NGa7vF9RWIpuKHbhDZQhk_FjoIHCWRKVWklNMC5eqKPoG-EyP05EFI7-Ibj5XfvNbf1Ql8BA2iCqmp4ARFF5usAk1NjSsrhcgZQwiytGfExFmbfQn5Tj1e8dKI_SOD9n08s6kJ1evsCORQFCpIGrxrs8FxadXC4q1OiE6sVUPDmVwXI1P4RgLOxdAxDU3C_YYV11DnFsMzAg" />
            <input type="hidden" name="r" value="l_S3N_aJ_xhMTS918M4YiIUH07GlsX4iLgYEAKcjPlw-1663135193-0-AR9FrnLcO5+3op1nwhxo75OIgjBwvaqFHTV7DYTxtmnzwfDWQpskXJ1TdOZANcUeJ/htZ+poUEaaVTfmjFA+s3v5l0L03cRxyZG/IfgzmTmjVRv1XEjWT8YaegGCRhudicQs6Cz9bO6o6Scyb5OoUYUWab3Caz3l9DI0/2ZiweY7fiYC4UBXkPJkaN67RkzRkukI1bl0OntSBxcKKycwMwzyb1COW9b8HWx4MjCy87xj8kQ0BE/lnhTbGB6S9g8zX2ujCSUyU8u8u0KcYPeI0Mvb2rucTzNkpFZwpFnFyu9g6PR3+eunuSH6CS522jIeN9NZNj6riYHFrhnnqBehNp5SkqFfjpVW9eLRhGdePGzuFOf2zOOwr4L8IACHjoiUky49RfyS8STuOfY94bFIU6upgCKBrxPh2cNqKOgFO9n9BhN3ewIhqej9h+y7C6zfzhP8yQAlFkc2YteR6fY5kx6RSe1ynYa8GDtq706FyWNOUPvzycRsHNEENMExaTDpAjEEHWeJbN0CUC6TeOhqXq2qKaDYihf4NMJn/hKwUc+k2KtMuDGUjWcqGLCnP0zwHG0E2pNNCrLn1o5unJUfbNkBvrXveRoegQke9BIrkrLeBiypuhP4+DxWryVj6RJ42WCwfXtKz50xcwZ3NG82j+0gyORt3MFeOCw4lHoBe/N7L9GWpCg8W/RE0+PKkEpV9yxD86zq8cf5HgzJPl79A26kol4IB+DriJ6T0ghnBXt0p+3HMCpaLMZZwIWQ0yRQLXGZNoX3c44nKxKjvGPFQBLhMQDxJldjH5YwK7cvsvZ75S2/+UoN4AEVXU9ZC403+B+GC+lPe2qbYasrezG14KpKPxrIArgTq4yEw3pZrtVVex60QnL/BZJyEEETINZrISBoq1zb0L+9y1DRlXdLFR9L3jHreazHXJAi41aryUd9BIdj0vIoHygT5n/yDZe3T8O+LG6fQ9w5JB52DlAxUorlAZpoNPpQNY8iN3mc0W4F6JC/7O2fEE3hXB2QOQ5fHM0gir6ekzxV3n4go7Qonbj3b4lXFcLH/Y6fWBbTSJcchGjHXojL2tP550k51EhH8T5k/obMmW4hBxRW4sHkgEIn241u4VZ6EavDbL0IL6xQKTMlcRA+iQJmCPX/BQ8kbdcFZ8p+hC3+bIjJv8+8aedSabLmyULxm9+0bNzEmcbzInnNomci7rjGTqotKZCxUTJHLoUuBujuhH5y3KudA6ewTJimJKN8ySbMs1EjzJCkkJYiICtSjMHu1SJGBEhRxR+CqYk+zYcSSur9pbRZuzCIqv6exWcu7DLdl4kAQSJ4opocNdsviqpci0WcUwgL57BqGXTDrKy2Wj0+ocaSJsGF0Qf605KCGgGyCEUsxoNEIBEss6kfkTiFQcDXDRXcIVQkykczT4UNrJJOQTFAIiHQaAetPPbwaxXTmcphW8l70HZA0CkcVeuMm+k3EdGMTi5z5rQNUzRe7yjyQ9ApVU2tr+ecKw+psby983VfS68U7AI6FulhrGMd5I+5D80NvRZcSo996kU0VS7sOLwqAG/dA+tu0AgG6aLTq/wjd5vk/e0vb8vp0hRbMAzl+rMoCRgmV+/rTSki6OYIWlvcMmThSwUJqEp603sE7jhAVcB2O4ZZHFNob41x3bsVE8VCUCcb5vR4cBjqU9mXsaqHp7KKbIc0jEKgLoq+HMwAJVRsCofoD21E20+kfHJcbcd4q4wvSAYajcmy/DZixUSkgHblSSaBnzfVxRyim4GlFsjqbykmpXYrBmLE0/Z5aLFjc6ipxtYKnAktY1Jz++d+Cs/RbRpO8yEAsoFNk9BF3ve78Nnutdeh8dyMlVoGuil9eg=="/>
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'managed',
            cNounce: '22986',
            cRay: '74a6e6313e384991',
            cHash: 'eb9c8b04e578f9b',
            cUPMDTk: "\/?__cf_chl_tk=E7vNErhJIa84spclKAVw2gt6HgcKtWIqLam_uX3iM3Y-1663135193-0-gaNycGzNB30",
            cFPWv: 'b',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly9zY3JhcC50Zi8=',
                ra: 'TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzEwNS4wLjAuMCBTYWZhcmkvNTM3LjM2',
                rm: 'R0VU',
                d: 'H2jpitvHx0wCpIYdPzdJ9qkUB9DpVs59/ly+G1+zOi3BSmNCF+wu7CwO+fQqOUwkHRx/lOFSC9/ZsJu6olCRRE0UiMTcA4lx8oFtul4CDdNjVWOui+Kn8EaeqzUuLltFYYaG9N33XASh5TLpUplms9C/1ny4ebnPLthgukF2xSE50gttY0DsyTB0fICTyoYEq2mBgw5bhHAjYC6oI5ZxerAr0f6/PGfxpHyMXIVcLChZHXxi1VUdtMPErr3Wu0AoPOk0b3PWTT8V21lBC86bIUxlN2Gua4smUJ81Rj/J2TtS/H866BptRqlyDo0SNA2BUxIpF+myxfFR74qRGcaLKVJsfAeZErpR3i82oXTsMbfvVVVI7MU4OcM8pAdMp9t5u8PWkiAZfVG1Mn1A44IYsl/q/I91mLBYxw2P/l6PWIZiW/4VbWw9bAhlBleQes5U7JuG4LtBvi9E5S+UngnXE04U4QA4y3jten4VhneDI7QJY256NJoX4qd9rB2au6QkCaI7IyXa/WTbKaIEQfAFu8pki51XkM1B00Y5ro70S5kC6QapytbrbN2CKPF787MeHItuRYnOEZVkQalVmKGirx3juUXtqHbQCq1jpu4JIooSW2JZh//JPZ3fWAm7/84uFOYcikuRj6BigQbaPH8nB3rzchHTjaGF2net5XiMoZZ9wtUmSOlUlnhQSHh9t3zU',
                t: 'MTY2MzEzNTE5My44MDEwMDA=',
                m: 'ZjzF6lzijj/IcLef82/YGqqi51ixUUoa/7tXTI1hpl0=',
                i1: 'r9GY6QE0DjSQ3BQ2lGPoFw==',
                i2: '9c1Rgt0EuqmfkWPQKmX7MA==',
                zh: 'z4cLlwNv4TqSGbD4saFAP5F9DL4az0JxyNlpxyo8deQ=',
                uh: 'hxTM763E8imxylwP68hH4R/wc4ym4Rsx7GMmWlye0AQ=',
                hh: '+DH0I8INQxL/O7QGmGqONtwzA+Tp0OqGNWsEfhA/dO0=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=74a6e6313e384991');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/managed/v1?ray=74a6e6313e384991';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/?__cf_chl_rt_tk=E7vNErhJIa84spclKAVw2gt6HgcKtWIqLam_uX3iM3Y-1663135193-0-gaNycGzNB30" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>74a6e6313e384991</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>

2022-09-14 08:59:56.7753 │ FATAL │                    RaffleService.StartAsync │ "System.Exception: Unable to make request
   at Scraps.Next.Services.RaffleService.GetStringAsync(String path) in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 584
   at Scraps.Next.Services.RaffleService.GetCsrfTokenAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 278
   at Scraps.Next.Services.RaffleService.StartAsync() in C:\Users\reese\source\repos\Scraps\Scraps.Next\Services\RaffleService.cs:line 165"
2022-09-14 08:59:56.7979 │ INFO  │                    RaffleService.StartAsync │ Stopped
```
the site opens and works fine
