### ISSUE TITLE
Tried to set scan delay really high to not get captchas

### ISSUE THREAD

**Issue by Barmem** [depthbomb/Scraps#60]
got int32 error, reduced to default, got this
```
System.NullReferenceException: Object reference not set to an instance of an object.System.NullReferenceException: Object reference not set to an instance of an object.
   at Scraps.Controls.WonRafflesControl.AddCookie() in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Controls\WonRafflesControl.cs:line 79
   at Scraps.Controls.WonRafflesControl.SetStatusFromCookie(String cookie) in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Controls\WonRafflesControl.cs:line 101
   at Scraps.Services.SettingsService.Set(String settingKey, Object settingValue) in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Services\SettingsService.cs:line 64
   at Scraps.Controls.SettingsControl._SaveSettingsButton_Click(Object sender, EventArgs e) in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Controls\SettingsControl.cs:line 92
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```

**Comment by Barmem** [comment]
![изображение](https://user-images.githubusercontent.com/70278808/218601251-7a9a540f-41b4-4ad1-bba0-cbb7e248bcf8.png)

**Comment by depthbomb** [comment]
This is likely related to #59, have you followed the instructions in my reply on that issue?
